// Copyright Fenerax Studios. All Rights Reserved.

#pragma once

//Printable keys
constexpr unsigned int KEYCODE_SPACE			= 32;
constexpr unsigned int KEYCODE_APOSTROPHE		= 39;  /* ' */
constexpr unsigned int KEYCODE_COMMA			= 44;  /* , */
constexpr unsigned int KEYCODE_MINUS			= 45;  /* - */
constexpr unsigned int KEYCODE_PERIOD			= 46;  /* . */
constexpr unsigned int KEYCODE_SLASH			= 47;  /* / */
constexpr unsigned int KEYCODE_0				= 48;
constexpr unsigned int KEYCODE_1				= 49;
constexpr unsigned int KEYCODE_2				= 50;
constexpr unsigned int KEYCODE_3				= 51;
constexpr unsigned int KEYCODE_4				= 52;
constexpr unsigned int KEYCODE_5				= 53;
constexpr unsigned int KEYCODE_6				= 54;
constexpr unsigned int KEYCODE_7				= 55;
constexpr unsigned int KEYCODE_8				= 56;
constexpr unsigned int KEYCODE_9				= 57;
constexpr unsigned int KEYCODE_SEMICOLON		= 59;  /* ; */
constexpr unsigned int KEYCODE_EQUAL			= 61;  /* = */
constexpr unsigned int KEYCODE_A				= 65;
constexpr unsigned int KEYCODE_B				= 66;
constexpr unsigned int KEYCODE_C				= 67;
constexpr unsigned int KEYCODE_D				= 68;
constexpr unsigned int KEYCODE_E				= 69;
constexpr unsigned int KEYCODE_F				= 70;
constexpr unsigned int KEYCODE_G				= 71;
constexpr unsigned int KEYCODE_H				= 72;
constexpr unsigned int KEYCODE_I				= 73;
constexpr unsigned int KEYCODE_J				= 74;
constexpr unsigned int KEYCODE_K				= 75;
constexpr unsigned int KEYCODE_L				= 76;
constexpr unsigned int KEYCODE_M				= 77;
constexpr unsigned int KEYCODE_N				= 78;
constexpr unsigned int KEYCODE_O				= 79;
constexpr unsigned int KEYCODE_P				= 80;
constexpr unsigned int KEYCODE_Q				= 81;
constexpr unsigned int KEYCODE_R				= 82;
constexpr unsigned int KEYCODE_S				= 83;
constexpr unsigned int KEYCODE_T				= 84;
constexpr unsigned int KEYCODE_U				= 85;
constexpr unsigned int KEYCODE_V				= 86;
constexpr unsigned int KEYCODE_W				= 87;
constexpr unsigned int KEYCODE_X				= 88;
constexpr unsigned int KEYCODE_Y				= 89;
constexpr unsigned int KEYCODE_Z				= 90;
constexpr unsigned int KEYCODE_LEFT_BRACKET		= 91;  /* [ */
constexpr unsigned int KEYCODE_BACKSLASH		= 92;  /* \ */
constexpr unsigned int KEYCODE_RIGHT_BRACKET	= 93;  /* ] */
constexpr unsigned int KEYCODE_GRAVE_ACCENT		= 96;  /* ` */
constexpr unsigned int KEYCODE_WORLD_1			= 161; /* non-US #1 */
constexpr unsigned int KEYCODE_WORLD_2			= 162; /* non-US #2 */

/* Function keys */
constexpr unsigned int KEYCODE_ESCAPE			= 256;
constexpr unsigned int KEYCODE_ENTER			= 257;
constexpr unsigned int KEYCODE_TAB				= 258;
constexpr unsigned int KEYCODE_BACKSPACE		= 259;
constexpr unsigned int KEYCODE_INSERT			= 260;
constexpr unsigned int KEYCODE_DELETE			= 261;
constexpr unsigned int KEYCODE_RIGHT			= 262;
constexpr unsigned int KEYCODE_LEFT				= 263;
constexpr unsigned int KEYCODE_DOWN				= 264;
constexpr unsigned int KEYCODE_UP				= 265;
constexpr unsigned int KEYCODE_PAGE_UP			= 266;
constexpr unsigned int KEYCODE_PAGE_DOWN		= 267;
constexpr unsigned int KEYCODE_HOME				= 268;
constexpr unsigned int KEYCODE_END				= 269;
constexpr unsigned int KEYCODE_CAPS_LOCK		= 280;
constexpr unsigned int KEYCODE_SCROLL_LOCK		= 281;
constexpr unsigned int KEYCODE_NUM_LOCK			= 282;
constexpr unsigned int KEYCODE_PRINT_SCREEN		= 283;
constexpr unsigned int KEYCODE_PAUSE			= 284;
constexpr unsigned int KEYCODE_F1				= 290;
constexpr unsigned int KEYCODE_F2				= 291;
constexpr unsigned int KEYCODE_F3				= 292;
constexpr unsigned int KEYCODE_F4				= 293;
constexpr unsigned int KEYCODE_F5				= 294;
constexpr unsigned int KEYCODE_F6				= 295;
constexpr unsigned int KEYCODE_F7				= 296;
constexpr unsigned int KEYCODE_F8				= 297;
constexpr unsigned int KEYCODE_F9				= 298;
constexpr unsigned int KEYCODE_F10				= 299;
constexpr unsigned int KEYCODE_F11				= 300;
constexpr unsigned int KEYCODE_F12				= 301;
constexpr unsigned int KEYCODE_F13				= 302;
constexpr unsigned int KEYCODE_F14				= 303;
constexpr unsigned int KEYCODE_F15				= 304;
constexpr unsigned int KEYCODE_F16				= 305;
constexpr unsigned int KEYCODE_F17				= 306;
constexpr unsigned int KEYCODE_F18				= 307;
constexpr unsigned int KEYCODE_F19				= 308;
constexpr unsigned int KEYCODE_F20				= 309;
constexpr unsigned int KEYCODE_F21				= 310;
constexpr unsigned int KEYCODE_F22				= 311;
constexpr unsigned int KEYCODE_F23				= 312;
constexpr unsigned int KEYCODE_F24				= 313;
constexpr unsigned int KEYCODE_F25				= 314;
constexpr unsigned int KEYCODE_KP_0				= 320;
constexpr unsigned int KEYCODE_KP_1				= 321;
constexpr unsigned int KEYCODE_KP_2				= 322;
constexpr unsigned int KEYCODE_KP_3				= 323;
constexpr unsigned int KEYCODE_KP_4				= 324;
constexpr unsigned int KEYCODE_KP_5				= 325;
constexpr unsigned int KEYCODE_KP_6				= 326;
constexpr unsigned int KEYCODE_KP_7				= 327;
constexpr unsigned int KEYCODE_KP_8				= 328;
constexpr unsigned int KEYCODE_KP_9				= 329;
constexpr unsigned int KEYCODE_KP_DECIMAL		= 330;
constexpr unsigned int KEYCODE_KP_DIVIDE		= 331;
constexpr unsigned int KEYCODE_KP_MULTIPLY		= 332;
constexpr unsigned int KEYCODE_KP_SUBTRACT		= 333;
constexpr unsigned int KEYCODE_KP_ADD			= 334;
constexpr unsigned int KEYCODE_KP_ENTER			= 335;
constexpr unsigned int KEYCODE_KP_EQUAL			= 336;
constexpr unsigned int KEYCODE_LEFT_SHIFT		= 340;
constexpr unsigned int KEYCODE_LEFT_CONTROL		= 341;
constexpr unsigned int KEYCODE_LEFT_ALT			= 342;
constexpr unsigned int KEYCODE_LEFT_SUPER		= 343;
constexpr unsigned int KEYCODE_RIGHT_SHIFT		= 344;
constexpr unsigned int KEYCODE_RIGHT_CONTROL	= 345;
constexpr unsigned int KEYCODE_RIGHT_ALT		= 346;
constexpr unsigned int KEYCODE_RIGHT_SUPER		= 347;
constexpr unsigned int KEYCODE_MENU				= 348;

//Modifier Keys
constexpr unsigned int MODIFIER_KEY_SHIFT		= 1;
constexpr unsigned int MODIFIER_KEY_CONTROL		= 2;
constexpr unsigned int MODIFIER_KEY_ALT			= 4;
constexpr unsigned int MODIFIER_KEY_SUPER		= 8;
constexpr unsigned int MODIFIER_KEY_CAPS_LOCK	= 16;
constexpr unsigned int MODIFIER_KEY_NUM_LOCK	= 32;